### ISSUE TITLE
Public Server Not Available

### ISSUE THREAD

**Issue by rawkode** [inexio/snmpsim#4]
The docs mention `snmpsim.try.thola.io`, but this doesn't resolve.

Is there a public server available?

**Comment by Lostboi** [comment]
Hey @rawkode 

yeah this server that you have mentioned should be available, it was just a DNS misconfiguration on our side so sorry about that.

**Comment by Hipska** [comment]
It does resolve, but doesn't respond to snmp.

**Comment by sberlin** [comment]
@Lostboi Seems like the DNS issue is back again:
```
nslookup snmpsim.try.thola.io 8.8.8.8
Server:         8.8.8.8
Address:        8.8.8.8#53

** server can't find snmpsim.try.thola.io: NXDOMAIN

```

**Comment by Lostboi** [comment]
Hey @sberlin,

let me have a look on it. I will fix it in a couple of days.

**Comment by stupalov** [comment]
@Lostboi hey, are you still supporting the project?
can you add maintainers so that this fork does not die either?..

**Comment by zatroa** [comment]
@landy2005 Yes, we are still supporting this project. We can add further maintainers. Just tell us if you are interesting in developing snmpsim.

**Comment by zatroa** [comment]
a public SNMP server is unfortunately very often victim of amplification DDoS attacks. Unfortunately, we cannot continue to offer this service. I have removed the corresponding pages.
