### ISSUE TITLE
Wrong link to demo instance documentation

### ISSUE THREAD

**Issue by Hipska** [inexio/snmpsim#5]
The readme points to http://snmplabs.thola.io/snmpsim/public-snmp-simulator.html as a demo instance, but this results in a 404.

**Comment by Hipska** [comment]
@zatroa @Lostboi still not resolved.

**Comment by zatroa** [comment]
a public SNMP server is unfortunately very often victim of amplification DDoS attacks. Unfortunately, we cannot continue to offer this service. I have removed the corresponding pages.

if someone wants to reactivate and run the public SNMP service just contact us.

**Comment by Hipska** [comment]
No, the Readme still points to that page..

**Comment by zatroa** [comment]
which URL?

**Comment by Hipska** [comment]
The README.md file hasn't been updated since 8 months. So I'm wondering how you think you removed it from the page?

**Comment by zatroa** [comment]
Sorry, I was really lost. README.md changed.

**Comment by Hipska** [comment]
Thanks!
